language: java
jdk:
  - openjdk17


#travis CI를 오직 master 브랜치에 push될 때만 수행
branches:
  only:
    - main

#travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
before_install:
  #  gradle 버전 변경
#  - sudo wget https://services.gradle.org/distributions/gradle-6.8-bin.zip
#  - sudo unzip -qq gradle-6.8-bin.zip
#  - export GRADLE_HOME=$PWD/gradle-6.8
#  - export PATH=$GRADLE_HOME/bin:$PATH
#  - gradle -version
#  - gradle wrap
  - chmod +x gradlew

before_script:
  - chmod -R +x gradlew

#master 브랜치에 푸시되었을 때 수행하는 명령어어
script: "./gradlew clean build"

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'julia2039@naver.com'

before_deploy:
  - zip -r hisujung_Backend_new *
  - mkdir -p deploy
  - mv hisujung_Backend_new deploy/hisujung_Backend_new.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #travis repo settings에 설정된 값
    secret_acccess_key: $AWS_SECRET_KEY #travis repo settings에 설정된 값
    bucket: hisujung-bucket
    # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉터리
    wait-until-deployed: true
    on:
      all_branches: true #해당 라인 추가
