language: java
jdk:
  - openjdk8


#travis CI를 오직 master 브랜치에 push될 때만 수행
branches:
  only:
    - main

#travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
before_install:
  - chmod +x gradlew

before_script:
  - chmod -R +x gradlew

#master 브랜치에 푸시되었을 때 수행하는 명령어어
script: "./gradlew clean build"

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'julia2039@naver.com'