language: java
jdk:
  - openjdk17


#travis CI를 오직 master 브랜치에 push될 때만 수행
branches:
  only:
    - main

#travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
before_install:
  - chmod +x gradlew

before_script:
  - chmod -R +x gradlew

#master 브랜치에 푸시되었을 때 수행하는 명령어어
script: "./gradlew clean build"

before_deploy:
  - FILE_NAME="$AWS_SECRET_KEY_Backend_new.zip"
  - zip -r $FILE_NAME *
  - mkdir -p deploy
  - mv $FILE_NAME deploy/$FILE_NAME
#  - mkdir -p before-deploy #zip에 포함시킬 파일들을 담을 디렉토리 생성
#  - cp scripts/*.sh before-deploy/
#  - cp appspec.yml before-deploy/
#  - cp build/libs/*.jar before-deploy/
#  - cp before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
#  - cd ../ && mkdir -p deploy #상위 디렉토리로 이동 후 deploy 디렉토리 생성
#  - mv before-deploy/before-deploy.zip deploy/$FILE_NAME #deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #travis repo settings에 설정된 값
    secret_acccess_key: $AWS_SECRET_KEY #travis repo settings에 설정된 값
    bucket: $AWS_SECRET_KEY-bucket
    # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉터리
    wait-until-deployed: true
    on:
      branch: main # main 브랜치에서만 배포#해당 라인 추가
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY

    bucket: $AWS_SECRET_KEY_bucket
    key: $FILE_NAME #빌드 파일을 압축해서 전달

    bundle_type: zip #압축 확장자
    application: springboot-flask-service #웹 콘솔에서 등록한 CodeDeploy 애플리케이션

    deployment_group: springboot-flask-service-group #웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main # main 브랜치에서만 배포


#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'julia2039@naver.com'




